version: "3"
services:
  agoras-actions:
    image: luisalejandro/agoras-actions:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/agoras-actions/app
    volumes:
      - .:/home/agoras-actions/app
    env_file:
      - .env