name: new-tw-post
author: Luis Alejandro Martínez Faneyth
description: GitHub Action for sending a tweet with option to add images.
inputs:
  consumer-key:
    description: Twitter consumer key from twitter developer app.
    required: true
  consumer-secret:
    description: Twitter consumer secret from twitter developer app.
    required: true
  oauth-token:
    description: Twitter OAuth token from twitter developer app.
    required: true
  oauth-secret:
    description: Twitter OAuth secret from twitter developer app.
    required: true
  status-text:
    description: Text to be published.
    required: true
  status-image-url-1:
    description: First image URL to be published.
    required: false
  status-image-url-2:
    description: Second image URL to be published.
    required: false
  status-image-url-3:
    description: Third image URL to be published.
    required: false
  status-image-url-4:
    description: Fourth image URL to be published.
    required: false

runs:
  using: docker
  image: docker://ghcr.io/luisalejandro/agoras-actions:latest
  args:
    - new-tw-post
    - ${{ inputs.consumer-key }}
    - ${{ inputs.consumer-secret }}
    - ${{ inputs.oauth-token }}
    - ${{ inputs.oauth-secret }}
    - ${{ inputs.status-text }}
    - ${{ inputs.status-image-url-1 }}
    - ${{ inputs.status-image-url-2 }}
    - ${{ inputs.status-image-url-3 }}
    - ${{ inputs.status-image-url-4 }}
