name: Build and push agoras docker image

on:
  workflow_dispatch:
  schedule:
    - cron: '00 3 * * 2'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Building docker image
        run: docker build -t luisalejandro/agoras-actions:latest docker
      - name: Login to Github Docker Registry
        run: echo ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pushing docker image
        run: |
          docker tag luisalejandro/agoras-actions:latest ghcr.io/luisalejandro/agoras-actions:latest
          docker push ghcr.io/luisalejandro/agoras-actions:latest
