name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: echo "test"

  approve:
    name: Approve pull request
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v3.1.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.REPO_PERSONAL_ACCESS_TOKEN }}"
      - name: Approve
        uses: hmarr/auto-approve-action@v3.1.0
        if: github.actor == 'LuisAlejandro'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  merge:
    name: Merge pull request
    runs-on: ubuntu-22.04
    needs: approve
    steps:
      - name: Merge
        uses: actions/github-script@v6
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.REPO_PERSONAL_ACCESS_TOKEN }}"
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
      - name: Merge
        uses: actions/github-script@v6
        if: github.actor == 'LuisAlejandro'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })