name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

  approve:
    name: Approve pull request
    runs-on: ubuntu-22.04
    needs: test
    if: github.actor == github.repository_owner || github.actor == 'dependabot[bot]'
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: "${{ github.actor == github.repository_owner && secrets.GITHUB_TOKEN || secrets.REPO_PERSONAL_ACCESS_TOKEN }}"

  merge:
    name: Merge pull request
    runs-on: ubuntu-22.04
    needs: approve
    if: github.actor == github.repository_owner || github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@v7
        with:
          github-token: "${{ github.actor == github.repository_owner && secrets.GITHUB_TOKEN || secrets.REPO_PERSONAL_ACCESS_TOKEN }}"
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
