name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        network:
          - twitter
          - facebook
          - instagram
          - linkedin
        action:
          - post
          - like
          - share
          - delete
          - last-from-feed
          - random-from-feed
          - schedule
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # - run: bash test.sh "${{ matrix.network }}-${{ matrix.action }}"

  approve:
    name: Approve pull request
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v3.2.0
        with:
          github-token: "${{ github.actor == 'LuisAlejandro' && secrets.GITHUB_TOKEN || secrets.REPO_PERSONAL_ACCESS_TOKEN }}"

  merge:
    name: Merge pull request
    runs-on: ubuntu-22.04
    needs: approve
    steps:
      - name: Merge
        uses: actions/github-script@v6
        with:
          github-token: "${{ github.actor == 'LuisAlejandro' && secrets.GITHUB_TOKEN || secrets.REPO_PERSONAL_ACCESS_TOKEN }}"
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })