name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
            network: twitter
            action: post
            twitter-consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
            twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
            twitter-oauth-token: ${{ secrets.TWITTER_OAUTH_TOKEN }}
            twitter-oauth-secret: ${{ secrets.TWITTER_OAUTH_SECRET }}
            status-text: ${{ secrets.STATUS_TEXT }}
            status-image-url-1: ${{ secrets.STATUS_IMAGE_URL_1 }}
            status-image-url-2: ${{ secrets.STATUS_IMAGE_URL_2 }}
            status-image-url-3: ${{ secrets.STATUS_IMAGE_URL_3 }}
            status-image-url-4: ${{ secrets.STATUS_IMAGE_URL_4 }}