name: test

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: "3.10"
    steps:
      - name: Testing script
        uses: ../../tweet-with-media
        env:
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FEED_URL: ${{ secrets.FEED_URL }}
