name: tweet-with-media
author: Luis Alejandro Martínez Faneyth
description: GitHub Action for sending a tweet with an image

runs:
  using: docker
  image: ../Dockerfile
  args:
    - tweet-with-media

branding:
  icon: at-sign
  color: blue
